# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7971a24b0745a12d1bf059d045212ec15ae9af66b2d63b1cd89f837b58940dd75e4887ddfe9f3875903128554de3b183c3c80a6299bb0f695a3a9885fc45b7b6

test:
  secret_key_base: 18f7e4de32d4153856c0a3908641051eab990a02198b49563b233aa9d1841b6545e1d15359de956465a1eed67e716403e9f49567a51f1330e3f92832da6e48e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
